//
//
//  Created by Ruan Tianyin on 2018/8/4.
//  Copyright © 2018年 Ruan Tianyin. All rights reserved.
//

import Foundation
import UIKit

class DataStorage {
    public static var names: [String] = ["Tartan", "Polka dot", "Greek Key","Chevron","Argyle","Paisley","Fleur-de-lis","Gingham","Yagasuri","Seigaiha"]
    public static var infos: [String] = ["Tartan / Plaid is a traditional design woven in wool in Scotland. It was first used to designate various Scottish clans, and now is used everywhere from skirts to blankets around the world.","Polka dot was originally the pattern on the costumes of flamenco dancers and other performers. They briefly came into popularity during the late 19th century, when polka dancing was popular, but haven’t really come into fashion again except for a brief spurt of popularity in 20th century.","This interlocking pattern—also known as meander or Greek fret—is a decorative border constructed from a continuous line, shaped into a repeated motif. It’s commonly used in Greece, and—although it’s often found in architectural details—today it’s used on everything from bedding to barware.","Characterized by a V-shaped zig-zags, Chevron originated as an insignia used in military or police uniforms to indicate rank or length of service, but has since become a mainstay on fabric and home decor accents.","Characterized by diamonds and an overlay of intercrossing diagonal lines, this pattern—which originated in 17th Century Scotland and usually considered preppy—is commonly used on things like socks and sweaters, but can also be found in flooring patterns, wallpaper, and home decor fabric.","Paisley, also called Persian pickles, is originated in Persia and India. It is the convergence of a stylized floral spray and a cypress tree: a Zoroastrian symbol of life and eternity. The 'bent' cedar is also the sign of strength and resistance but modesty.","A symbol of European monarchy, particularly French monarchy, since medieval times, the fleur-de-lis represents a lily. The stylized design shows off three or four petals with a band near the bottom. It's a very formal, traditional design.","This country classic shows off white plus another color woven into a checkerboard pattern. While gingham is very common in country decor, it's a good choice for any casual decorating style and mixes well with many other designs.","Having a pattern of shot-arrows that never return,  Yagasuri pattern has been used for a bride’s costume. The design of Yagasuri is pretty sharp, yet blurred arrows give an impression of softness.From the Meiji era to the Taisho era, it was worn as school girls’ outfit. It also symbolizes a lucky charm.","The word Seigaiha has its origin in the dance from ancient Japanese court music. Seigaiha, meaning “blue ocean waves”, is considered a symbol of peace, good luck, and fortune. This pattern has been typically used in Egypt and Persia (Iraq)."]
    public static var image1:[UIImage] = [#imageLiteral(resourceName: "Tartan"),#imageLiteral(resourceName: "polkadot"),#imageLiteral(resourceName: "greekkey"),#imageLiteral(resourceName: "chevron"),#imageLiteral(resourceName: "Argyle"),#imageLiteral(resourceName: "paisley"),#imageLiteral(resourceName: "fleur-de-lys"),#imageLiteral(resourceName: "gingham"),#imageLiteral(resourceName: "yagasuri"),#imageLiteral(resourceName: "Seigaiha")]
    public static var image2:[UIImage] = [#imageLiteral(resourceName: "tartan2"),#imageLiteral(resourceName: "Polkadot2"),#imageLiteral(resourceName: "Greekkey2"),#imageLiteral(resourceName: "chevron2"),#imageLiteral(resourceName: "argyle2"),#imageLiteral(resourceName: "paisley2"),#imageLiteral(resourceName: "fleur_de_lis2"),#imageLiteral(resourceName: "gingham2"),#imageLiteral(resourceName: "yagasuri2"),#imageLiteral(resourceName: "seigaiha2")]

}

class Asia {
    public static var names: [String] = ["Paisley","Yagasuri","Seigaiha"]
    public  static var infos: [String] = ["Paisley, also called Persian pickles, is originated in Persia and India. It is the convergence of a stylized floral spray and a cypress tree: a Zoroastrian symbol of life and eternity. The 'bent' cedar is also the sign of strength and resistance but modesty.", "Having a pattern of shot-arrows that never return,  Yagasuri pattern has been used for a bride’s costume. The design of Yagasuri is pretty sharp, yet blurred arrows give an impression of softness.From the Meiji era to the Taisho era, it was worn as school girls’ outfit. It also symbolizes a lucky charm.", "The word Seigaiha has its origin in the dance from ancient Japanese court music. Seigaiha, meaning “blue ocean waves”, is considered a symbol of peace, good luck, and fortune. This pattern has been typically used in Egypt and Persia (Iraq)."]
    public static var image1: [UIImage] = [
        #imageLiteral(resourceName: "paisley"),#imageLiteral(resourceName: "yagasuri"),#imageLiteral(resourceName: "Seigaiha")]
}

class Europe {
    public static var names: [String] = ["Fleur-de-lis","Gingham","Argyle","Chevron", "Greek Key", "Polka dot","Tartan"]
    public static var infos: [String] = ["A symbol of European monarchy, particularly French monarchy, since medieval times, the fleur-de-lis represents a lily. The stylized design shows off three or four petals with a band near the bottom. It's a very formal, traditional design.","This country classic shows off white plus another color woven into a checkerboard pattern. While gingham is very common in country decor, it's a good choice for any casual decorating style and mixes well with many other designs.","Characterized by diamonds and an overlay of intercrossing diagonal lines, this pattern—which originated in 17th Century Scotland and usually considered preppy—is commonly used on things like socks and sweaters, but can also be found in flooring patterns, wallpaper, and home decor fabric.","Characterized by a V-shaped zig-zags, Chevron originated as an insignia used in military or police uniforms to indicate rank or length of service, but has since become a mainstay on fabric and home decor accents.","This interlocking pattern—also known as meander or Greek fret—is a decorative border constructed from a continuous line, shaped into a repeated motif. It’s commonly used in Greece, and—although it’s often found in architectural details—today it’s used on everything from bedding to barware.","Polka dot was originally the pattern on the costumes of flamenco dancers and other performers. They briefly came into popularity during the late 19th century, when polka dancing was popular, but haven’t really come into fashion again except for a brief spurt of popularity in 20th century.","Tartan / Plaid is a traditional design woven in wool in Scotland. It was first used to designate various Scottish clans, and now is used everywhere from skirts to blankets around the world."]
    public static var images1: [UIImage] = [#imageLiteral(resourceName: "fleur-de-lys"),#imageLiteral(resourceName: "gingham"),#imageLiteral(resourceName: "Argyle"),#imageLiteral(resourceName: "chevron"),#imageLiteral(resourceName: "greekkey"),#imageLiteral(resourceName: "polkadot"),#imageLiteral(resourceName: "Tartan")]
}

class Africa {
    public static var names: [String] = ["Adinkra","Kente"]
    public static var infos: [String] = ["Adinkra are used extensively in fabrics and pottery among the Ashantis of Ashanti Kingdom. The symbols have a decorative function but also represent objects that encapsulate evocative messages that convey traditional wisdom, aspects of life or the environment.", "Kente a type of silk and cotton fabric made of interwoven cloth strips and is native to the Akan ethnic group of West Ghana. Kente comes from the word kenten, which means basket in Akan dialect Asante."]
    public static var image1: [UIImage] = [#imageLiteral(resourceName: "Adinkra"),#imageLiteral(resourceName: "kente")]
}

